### ISSUE TITLE
Better explanation of functions in docs

### ISSUE THREAD

**Issue by strengejacke** [easystats/modelbased#59]
Actually, I'm always confused with what the functions do. The help-files are not helpful yet for (new) users. I think we should add more information to the docs (details section?), explaining the functionality or showing the differences between functions.

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/p3RAfTA6Jxq4o/giphy.gif)

**Comment by DominiqueMakowski** [comment]
But yeah, I agree, this package is underrated (because of ggeffects competition? ^^) and yet it's definitely the one that I use the most and that is the most useful IMO.

the `visualisation_matrix()` function is my diamond ☺️ 

so I agree, it needs more love. As you guys are fairly "new" to it you might be better positioned at trying it out, testing features and its API and get familiar with it to then outline directions for improvement

**Comment by mattansb** [comment]
I use emmeans directly - I work mostly with factorial data, and 99% of the time I want very very specific contrasts / plot estimates 🤷‍♂️

**Comment by DominiqueMakowski** [comment]
yes, modelbased is more for non-emmeans savy users to do exploratory / visualisation aimed stuff, and also cause it has a tidy/easy output

**Comment by mattansb** [comment]
Absolutely! Some of my students last semester used `modelbased` in an assignment - I was very proud 😊

**Comment by DominiqueMakowski** [comment]
The docs are now rather good; but #108 might push this even further
