### ISSUE TITLE
Inconsistent behavior between insight::get_predicted() and modelbased::estimate_response()

### ISSUE THREAD

**Issue by bwiernik** [easystats/modelbased#98]
The behavior of the `predict` argument is inconsistent between `insight::get_predicted()` and `modelbased::estimate_response()`. In get_predicted(), `predict = "response"` produces a confidence interval, but in estimate_response(), it produces a prediction interval. I'm guessing the reasoning for this is to make estimate_response() more consistent across frequentist and Bayesian models, but it does produce some unexpected results for me as I am exploring the various features of the easystats-verse. That the intervals are prediction intervals is also not documented in the help file.

```r
library(modelbased)
library(insight)
m <- lm(mpg ~ factor(cyl) + log(hp), data = mtcars)

er <- head(modelbased::estimate_response(m))
gp_c <- head(as.data.frame(insight::get_predicted(m, ci_type = "confidence")))
gp_p <- head(as.data.frame(insight::get_predicted(m, predict = "prediction")))

er
gp_c
gp_p
```

(Beyond this, it's also a little confusing to me that `get_predicted()` controls the interval type with `predict` whereas `get_predicted_ci()` controls it with `interval`. Perhaps it would be good to make those consistent to use `predict` for link/response and `interval` for confidence/prediction/posterior prediction (that is, an interval including uncertainty in both mean and sigma as in a Bayesian model)?)

To that last point, perhaps a solution is to separate `predict` and `interval` into two arguments consistently and then to make `interval` default to "prediction" or "pp" or similar in `estimate_response()`?

**Comment by strengejacke** [comment]
We had a longer discussion about the API / naming of arguments over here:
https://github.com/easystats/insight/issues/310

Feel free to respond there, we might re-open that issue to continue that discussion.

**Comment by DominiqueMakowski** [comment]
Yes, the modelbased package is pretty much in a state of being reworked and rescoped (will probably focus on high-level "smart" functions that can automatically detect the user's interest in the models and prepare visualizations for them), since the recent outsourcing of the prediction machinery to insight::get_predicted. We indeed had quite a long discussion about it before finally settling on an API that is practical, intuitive and hopefully not-too-nonsensical statistically

**Comment by DominiqueMakowski** [comment]
Oops I read the first part of your comment too quickly @bwiernik apologies, but yes you're right modelbased is inconsistent because I just changed its API to follow a bit more closer the new insight without breaking too much the old API that is still on cran... But to be honest I don't know exactly what to do here so any suggestions are very welcome

**Comment by DominiqueMakowski** [comment]
But I think that modelbased should be as much intuitive as possible, which is hard considered that the whole prediction framework is quite convoluted :/

**Comment by DominiqueMakowski** [comment]
I think discrepancies have been mostly resolved, since it follows now closely the get_predicted API
