### ISSUE TITLE
Combined data frame with data/predicted/resid

### ISSUE THREAD

**Issue by bwiernik** [easystats/modelbased#99]
One thing that `broom::augment()` makes easy that seems difficult currently with insight is to get a combined data frame with the input data, predictions (+SEs/intervals), and residuals. Such a data frame is potentially useful for:

1. Constructing plots that overlay raw data with model predictions.
2. Detailed model diagnositics, such as examinate of residual correlations with individual predictors (versus only against the fitted values as in `check_model()` plots).

Do you think we could add a function that calls get_data(), get_predicted(), and get_data() and merging them by rowname? Thoughts on a name? 

It would be possible of course for users to that manually, but I'm thinking about cases like my intro regression students where I try to limit the amount of unique R data processing steps I introduce at once. This is especially an issue with things like missing data that might cause rows not to be aligned across various outputs, necessitating merging rather than cbinding (e.g., https://github.com/easystats/insight/issues/341).

The other things that augment() includes are diagnostic statistics hat, cooksd, standardized residuals, and leave-one-out estimates (sigma, dffits, dfbeta). I don't see much need for these combined with predicted/resid/raw data, but it might be useful to export a function for that data frame in performance outside of the internal functions used by `check_model()`.

**Comment by strengejacke** [comment]
Ok, then I move this issue to modelbased.

**Comment by bwiernik** [comment]
That make sense to me to move it to modelbased if we push that package forward as the user-facing one for augment-y sort of stuff. 

How about if we just add an argument to include the residuals in the estimate_response() family? (Or just include them always?)

For the response variable, I think it might be reasonable to just include it automatically if present.

**Comment by bwiernik** [comment]
Oh! Adding the response variable to the data frame could then speak to a `plot()` method to generate a simple data+fitted line prediction plot.

**Comment by strengejacke** [comment]
But shouldn't `get_data()` already include the response?

**Comment by strengejacke** [comment]
https://twitter.com/bmwiernik/status/1383847868285394944

Nice suggestions! 😄

**Comment by bwiernik** [comment]
> But shouldn't get_data() already include the response?

It doesn't include predictions, intervals, or residuals. The idea here is to have a function that returns response, predictors, predictions, uncertainty, and residuals in one go. 

The prediction functions (in the `modelbased::estimate_response()` family) give the predictors, predictions, and uncertainty but omit the response and residuals. I think that the response should be included—I don't see any reason to omit it, and I also think that residuals should either be included automatically or available as an argument.

**Comment by strengejacke** [comment]
OK, got it. I just thought that, since you mentioned data/residuals/predictions in your title and we had a quick draft using get_data, get_predicted and get_residuals, that we already would have predictors and response included.

**Comment by bwiernik** [comment]
Those all made more sense before we moved the issue over to modelbased. Once I saw what was currently reported in `estimate_response()`, I thought I made sense to just beef up that function a bit versus making a new function (and trying to find a non-confusing name for it).

**Comment by DominiqueMakowski** [comment]
> How about if we just add an argument to include the residuals in the estimate_response() family? (Or just include them always?)
> For the response variable, I think it might be reasonable to just include it automatically if present.

I would say that, at `modelbased` level, it makes sense to make the distinction between visualization-aimed predictions and original-data-based predictions. The former (embodied by the `estimate_relation` / `estimate_link` functions - temporary name based on the `predict` type argument of get_predicted), by default, generates predictions on a [visualization matrix](https://easystats.github.io/modelbased/articles/visualisation_matrix.html). The latter (`estimate_predictions` / `estimate_response` - currently they are the same) by default makes predictions on the model's data.

So for the functions that make predictions on the data, I'd say we can add by default the original response and the residuals. That would further differentiate the two sets of functions following the two common goals of model-based predictions. 

> Oh! Adding the response variable to the data frame could then speak to a plot() method to generate a simple data+fitted line prediction plot.

Absolutely! I think the future big set of features for `modelbased` is a stronger connection to plots, so that you can run `plot()` on the modelbased functions' output and it tries to give you a meaningful/appropriate plot. I have started initiated yesterday a first move towards that called `visualisation_recipe()` that would try to infer from the input the type of plot and the plot properties (aesthetics, axes titles, etc.). This could be used by `see` to then automatically make a plot :)


> I thought I made sense to just beef up that function a bit versus making a new function

I think so too

**Comment by DominiqueMakowski** [comment]
@bwiernik Feel free to add that feature and yourself in the description :)

We can add to this:

https://github.com/easystats/modelbased/blob/1d1871e4bfc8e3d322e688fe7a99515260aa220b/R/estimate_predicted.R#L66

an `include_residuals` arg that is set to `"auto"`:

- if `"auto"`, becomes `TRUE` if `data = NULL` (or if provided data matches data from get_data())? Otherwise, if `data="grid"`, then false (but no warnings)
- if explicitly set to `TRUE`, if data is `"grid"`, or does not match `get_data`, throw warning

what do you think?

**Comment by bwiernik** [comment]
If new data are provided and they include the response variable, I think computing the residual makes sense?

**Comment by DominiqueMakowski** [comment]
Ah yes indeed didn't think of that possibility

**Comment by DominiqueMakowski** [comment]
This has been included. Closing this issue, but follow-up could be thought of in new issues (I'm thinking of automatic plotting with the residuals/original response)
